components/LandingComponents.tsx/HorizontalTransitionVideoInfo.tsx
components/LandingComponents.tsx/VerticalTransitionVideoInfo.tsx
pages/index.tsx

content ratio changed

---

components/LandingComponents.tsx/HorizontalTransitionVideoInfo.tsx
pages/index.tsx

HorizontalTransitionVideoInfo width ratio updated

HorizontalTransitionVideoInfo width ratio updated

---

components/RAndDCompoenents/Partnership.tsx

Partnership bottom container error fixed

Partnership bottom container error fixed

---

components/CompanyComponents/HistoryComp.tsx
components/CompanyComponents/Member.tsx
components/CompanyComponents/PhilosophyComp.tsx
components/LandingComponents.tsx/HorizontalSlidingCard.tsx
components/LandingComponents.tsx/VerticalSlidingCard.tsx
components/RAndDComponents/LCA.tsx
components/RAndDComponents/Partnership.tsx
pages/company/index.tsx
pages/index.tsx
pages/randd/index.tsx
styles/commonStyles.ts

**작성자**
최정윤
- 기존 font-size가 vw 단위로 되어있는 것 모두 px 로 변경 
- 반응형 구조는 유지 - 컴퓨터 화면의 경우에만 px로 수정 
- 축소 시 화면 중앙으로 컴포넌트가 배치되도록 수정 
- Section의 title과 subTitle 스타일 - `style-components`이용하여 컴포넌트 화

[BugFix] Resolving problems that cannot be zoomed in 

---

components/CompanyComponents/HistoryComp.tsx
components/CompanyComponents/PhilosophyComp.tsx
functions/TransitionVariants.tsx

최정윤
- company page의 phillosophy  폰트 사이즈 수정
- company page의  history : 축소 시 글씨 잘리는 문제 해결 
- margin, padding 단위 수정함

[BugFix] Resolves that UI is ruined at company page

---

components/RAndDComponents/Partnership.tsx

최정윤 
- 파트너십 관련 컴포넌트 축소해도 사진 비율 유지되도록 수정

[BugFix] Fix Parnership component of RnD page

---

components/CompanyComponents/PhilosophyMobile.tsx
components/RAndDComponents/LCAMobile.tsx
components/RAndDComponents/Partnership.tsx
components/RAndDComponents/PartnershipMobile.tsx
pages/company/index.tsx
pages/index.tsx
pages/randd/index.tsx

최정윤 
- 랩탑 화면에서 확대 시 컴포넌트 UI 깨지는 문제 해결 
- R&D 페이지 
- Welcome section: 크기 수정 
- LCA : 컴포넌트 겹침 문제 해결 
- Partnership : 컴포넌트 겹침 문제 해결 , 이미지 비율 망가지는 문제 해결 
- Company 페이지
- Welcome section: 크기 수정 
- Phillosophy  : 불필요한 background 컬러제거

[BugFix] Resolves UI corruption when zoomed in

---

functions/MemberContent.tsx
pages/product/ciet/index.tsx

최정윤
- member에 기록된 이름 오타 수정 
- ciet 링크 : 테스트 링크 -> 본 서버 링크 로 수정

[FeatDone] Update ciet link and members name

---

components/CompanyComponents/PhilosophyComp.tsx
components/CompanyComponents/PhilosophyMobile.tsx

최정윤
- philosophy 컴포넌트 : 글씨 크기에 대한 반응형 변환 기준을 2xl로 변경
- philosophy mobile 컴포넌트 : 최대 크기로 확대 시 landscape/portrait 에 따라 다르게 보이도록 수정

[BugFix] Fix bugs that philosophy UI collapsed when zoom in 

---

components/LandingComponents.tsx/LandingMobile.tsx
pages/index.tsx

최정윤 
- 모바일 화면에서 landig page 모바일 컴포넌트 보여지도록 수정

[Bugfix] Add mobile component to landing page 

---

components/PopUp.tsx

최정윤
- 모바일 팝업 하단의 글씨 크기 및 border line 단위 수정

[BugFix] Fix metric of moblie pop up

---

components/RAndDComponents/PartnershipCard.tsx

최정윤 
- 파트너십 회사 선택 시 하단에 민트 영역 나타나는 기능 추가 (실수로 주석 처리함)

[FeatDone] Add mint bottom bar to partnership component 

---

components/CompanyComponents/Members.tsx

[Bugfix] Set arrow container to resize arrow

---

components/LandingComponents.tsx/ReduceCard.tsx
components/LandingComponents.tsx/RemoveCard.tsx
components/LandingComponents.tsx/ReportCard.tsx
hooks/useHover.ts
pages/index.tsx
styles/commonStyles.ts
tailwind.config.js

최정윤 
- 버튼 크기  CIS, CIET 같게 수정
-  reduce 카드 hover effect 수정 
-  remove 카드 , report  카드  hover effect 추가

[FeatDone] Update landing detail  

---

components/Layout.tsx
components/PopUp.tsx
constants/enum/cookie_key.enum.ts
package.json
yarn.lock

최정윤 
- 팝업에 "오늘 하루 안보기 " 체크박스 추가 
- 쿠키 설정을 통해 하루동안 팝업 등장 안하도록 구현

[FeatDone] Add "not show today" checkbox function

---

components/LandingComponents.tsx/MeasureCard.tsx
components/LandingComponents.tsx/ReduceCard.tsx
components/LandingComponents.tsx/ReduceCards.tsx
components/LandingComponents.tsx/RemoveCard.tsx
components/LandingComponents.tsx/RemoveCards.tsx
components/LandingComponents.tsx/ReportCard.tsx
pages/index.tsx
styles/commonStyles.ts
tailwind.config.js

최정윤 
- 랜딩 페이지 모바일 버전 구현 
- measure section
- reduce section
- remove section 
- report section

[FeatDone] Add mobile version landing page

---

components/LandingComponents.tsx/MeasureCard.tsx

최정윤 
- measure 카드의 제목 크기 : 기존보다 작게 수정

[Style] Downsize the font of measure card's title 

---

components/CompanyComponents/Members.tsx

최정윤
- member section 모바일 버전 스크롤에 snap 스크롤 기능 추가

[FeatDone] Add snap scroll to member section

---

components/CompanyComponents/HistoryCard.tsx

최정윤 
- 모바일 버전에서, 2021년도 클릭 시 2022년이 펼쳐지는 문제 해결

[Bugfix] Make 2022 not be opened when 2021 clicked

---

components/RAndDComponents/Arrow.tsx
components/RAndDComponents/PartnershipCard.tsx

최정윤 
- 위쪽 방향 화살표 두께 얇아진 문제 해결 
-  nav 바에서 rnd 탭 선택 시 partnership으로 스크롤 되는 문제 수정

[BugFix] Fix bugs in RnD page (Partnership scroll,  Up Arrow)

---

components/CompanyComponents/MemberCard.tsx
components/LandingComponents.tsx/ReduceCard.tsx

최정윤 
- 모바일 카드에서 overflow-clip 안먹히는 문제 해결 
- reduce 모바일 카드 - 설명 부분 글씨 너무 작은 문제 해결

[Bugfix] Fix member card img not clipped and update text size of reduce card (mobile ver)  

---

components/LayoutComponents/Hamburger/HamburgerMenu.tsx

최정윤 
- 모바일 nav 바 수정 
- product 버튼 누르면 바로 ciet 랜딩 페이지로 이동되게 수정 
- 햄버거 버튼, x 버튼의 높이 :  vh 단위로 수정

[FeatDone] Update mobile nav - function of product button & update icon size

---

components/Error.tsx
pages/403.tsx
pages/404.tsx
pages/500.tsx
pages/503.tsx
pages/504.tsx
pages/505.tsx

최정윤 
- 403, 404, 500, 503, 504, 505 에러 페이지 생성

[FeatDone]  Add error page

---

components/LandingComponents.tsx/MeasureCard.tsx
components/LandingComponents.tsx/RemoveCards.tsx

최정윤 
- 모바일 버전 measure section : 항상 펼쳐져 있도록 수정 
- 모바일 버전 remove section : 항상 펼쳐져 있도록 수정

[FeatDone] Update landing page mobile ver to always open the content 

---

components/RAndDComponents/PartenershipMobileContentCard.tsx

최정윤 
- 파트너쉽 모바일 이미지 왜곡 해결안된 문제 수정

[Bugfix] Fix partnership img distorted in mobile ver

---

components/LandingComponents.tsx/MeasureCard.tsx
components/LandingComponents.tsx/ReduceCard.tsx
components/LandingComponents.tsx/ReduceCards.tsx
components/LandingComponents.tsx/RemoveCard.tsx
components/LandingComponents.tsx/ReportCard.tsx
pages/index.tsx
styles/commonStyles.ts

최정윤 
- 랜딩 페이지의 모든 섹션 : 한 화면에서 내용까지 확인할 수 있도록 크기 축소

[Style] Reduce size of landing page components

---

components/LandingComponents.tsx/MeasureCard.tsx
components/LandingComponents.tsx/ReduceCard.tsx
components/LandingComponents.tsx/ReduceCards.tsx
components/LandingComponents.tsx/RemoveCard.tsx
components/LandingComponents.tsx/RemoveCards.tsx
components/LandingComponents.tsx/ReportCard.tsx
components/PopUp.tsx
components/RAndDComponents/PartenershipMobileContentCard.tsx
components/RAndDComponents/Partnership.tsx
components/RAndDComponents/PartnershipCard.tsx
components/RAndDComponents/PartnershipMobile.tsx
functions/PartnershipContent.tsx
pages/company/index.tsx
pages/randd/index.tsx

최정윤 
- img 태그를 next/image 의 Image 태그로 대체 
- next/image의 size 속성값을 이용하여 loading 속도 줄임

[FeatDone] Optimzie img with next/image

---

components/CompanyComponents/HistoryCard.tsx
components/CompanyComponents/MemberCard.tsx
components/CompanyComponents/Members.tsx
components/CompanyComponents/PhilosophyComp.tsx
pages/company/index.tsx
styles/globals.css

최정윤
- company 페이지의 컴포넌트들 크기 축소 
- philosophy
- members
- history

[Style] Reduce size of company page

---

components/RAndDComponents/LCA.tsx
components/RAndDComponents/LCACard.tsx
components/RAndDComponents/LCAIcon.tsx
components/RAndDComponents/Partnership.tsx
components/RAndDComponents/PartnershipCard.tsx
pages/randd/index.tsx
styles/commonStyles.ts

최정윤 
- LCA PC 버전 컴포넌트 크기 축소 
- LCA 모바일 아이콘 : 제목 두껍게 수정
- section title 크기 축소

[Style] Update R&D page style 

---

components/LayoutComponents/Hamburger/HamburgerMenu.tsx
components/LayoutComponents/NavBar.tsx

최정윤
- pc nav바의 product hover시 product들  모두 나타나도록 수정 
- mobile hamberger nav의 product 클릭 시 product들  모두 나타나도록 수정

[FeatDone] Update nav to show all product 

---

components/RAndDComponents/LCA.tsx
components/RAndDComponents/LCACard.tsx
pages/randd/index.tsx

최정윤 
- RnD 컴포넌트들 중앙 배치 
- LCA 섹션: 높이 작게 수정

[Style] Update style of LCA page

---

components/LayoutComponents/Footer.tsx
components/RAndDComponents/Partnership.tsx
pages/company/index.tsx
pages/index.tsx
pages/randd/index.tsx

[Style] Add scroll snap style

---

pages/company/index.tsx

최정윤 
- 히스토리 섹션 가운데 정렬 안되어있는 문제 해결

[Style] Set history components to center

---

components/RAndDComponents/Partnership.tsx
pages/randd/index.tsx

최정윤 
- 컴포넌트들이 잘 보이도록 snap position 수정

[Style] Update snap position of RnD components

---

pages/company/index.tsx
pages/index.tsx
pages/randd/index.tsx

최정윤 
- 페이지 이동 시 맨 위로 스크롤 되도록 설정

[Style] Change to scroll to top when page changed

---

components/Layout.tsx

최정윤 
- 하루동안 보지 않기를 체크했음에도, 다른 페이지 들어갔다 다시 홈으로 돌아가면 팝업 계속 나타나는 문제 해결 
- 기존에는 새로고침(홈페이지에 새로 들어가는 경우)에만 쿠키 적용이 되었음.

[Bugfix]  Fix showing pop up after checked 'not show today'

---

components/RAndDComponents/Partnership.tsx

최정윤 
- partnership section의 이미지 와 글씨 동시에 확인할 수 있도록 scroll snap 추가

[FeatDone] Add snap to partnership img section

---

pages/company/index.tsx

최정윤 
- history section의 snap position: 좀 더 내용 확인하기 쉽도록 변경

[FeatDone] Update snap position of history section

---

components/RAndDComponents/PartenershipMobileContentCard.tsx
components/RAndDComponents/PartnershipMobile.tsx

최정윤 
- partnership mobile 사진 부분의 불필요한 공백 제거

[Style] Remove blank of img of partnership mobile

---

components/LandingComponents.tsx/MeasureCard.tsx

최정윤 
- 검은색 div 튀어나오는 문제 해결 
- 코드 리팩토링

[Bugfix] Fix Measure Card Style

---

components/CompanyComponents/HistoryCard.tsx
components/LandingComponents.tsx/MeasureCard.tsx
components/LandingComponents.tsx/RemoveCard.tsx
components/LandingComponents.tsx/ReportCard.tsx
pages/randd/index.tsx
tailwind.config.js

최정윤 
- Landing page mobile card 컴포넌트 크기 수정 
- Measure, report, LCA : lg 사이즈 모니터 부터 mobile ver 나오도록 설정 
- History card 모바일 버전 height 수정 
-  reduce card : lg 사이즈 모니터에서 글자 크기 수정

HOMEPAGE-3 Update style of mobile ver 

---

components/LCAComponents/SectionDetail.tsx
pages/lca/index.tsx

안경호
- LCA 프로젝트 안내 페이지 디자인 수정
- 신규 디자인으로 반영

HOMEPAGE-23 [FeatDone] LCA project guide page re-design

---

components/LayoutComponents/Hamburger/HamburgerMenu.tsx
components/LayoutComponents/NavBar.tsx
pages/index.tsx
styles/commonStyles.ts

최정윤
-  기존 cis 페이지로 링크되어있는 것 => product/cis 로 변경

HOMEPAGE-26 [FeatDone] Update to link to /product/cis

---

components/LayoutComponents/Hamburger/HamburgerMenu.tsx
components/LayoutComponents/NavBar.tsx
components/Products/CietLanding/Process/CietProcessSection.tsx
components/Products/CietLanding/Process/NormalProcessSection.tsx
components/Products/CietLanding/Process/SharedStyle.ts
components/Products/CisLanding/Features/Details/Feature.tsx
components/Products/CisLanding/Intro/Intro.tsx
components/Products/CisLanding/ShortCut/ShortCut.tsx
components/Products/CisLanding/UseCase/UseCase1.tsx
components/Products/CisLanding/UseCase/UseCase2.tsx
components/Products/CisLanding/UseCase/UseCase3.tsx
components/Products/Common/Report/Report.tsx
package.json
pages/product/ciet/index.tsx
pages/product/cis/index.tsx
yarn.lock

최정윤
- Image의 속성을 priority로 설정하여 preloading 되도록 변경

[ETC] Improve performance of image loading 

---

components/HomeComponents/CardNonText/CarbonCycle.tsx
components/HomeComponents/CardNonText/RightNonText.tsx
components/HomeComponents/MobileCards/MobileCards.tsx
components/HomeComponents/PcCards/PcCards.tsx
components/HomeComponents/ProductButtons/ProductButtons.tsx

최정윤
- 홈 화면 버튼 수정 
- 홈 화면 왼쪽 카드 선택 시 오른쪽 카드 레이아웃 망가지는 문제 해결 
- 모바일 오른쪽카드 글씨 깨지는 문제 해결

[ETC] Update style of right card and buttons

---

components/HomeComponents/CardNonText/CarbonCycle.tsx

- 최정윤
- 아이콘 초깃값 퍼센트로 설정되어있어, 첫 렌더링 시 크게 나타나는 문제 해결

[BugFix] Fix lca arrow shown big when first rendering

---

components/HomeComponents/CardNonText/LeftNonText.tsx
components/HomeComponents/CardNonText/RightNonText.tsx
components/Layout.tsx
components/Products/CisLanding/Features/Features.tsx
components/Products/Common/BetaInfo/BetaInfo.tsx
components/Products/Common/ReportModal/ReportModal.tsx
components/Products/Common/Summary/Summary.tsx

최정윤
- LCA 팝업 숨김 처리 
- 제품 소개 페이지 - 베타, 요약 섹션 이미지 최적화

[ETC] Hide popup , image optimization , fix CIS to GreenERP

---

components/HomeComponents/MobileCards/MobileCards.tsx

최정윤
- 모바일 카드 클릭 했을 때도 카드 이동되도록 변경

[FeatDone] Add click event to mobile card

---

components/Products/CisLanding/Intro/Intro.tsx

[BugFix] Fix typo and inaccurate file

---

components/Products/Common/BetaInfo/BetaInfo.tsx
components/Products/Common/ReportModal/ReportModal.tsx

최정윤
- 제품 페이지: 베타 서비스 섹션의 이미지 로딩 최적화

[FeatDone] Optimize img loading of beta info section

---

components/Products/Common/Report/Report.tsx

최정윤
- 제품 소개 리포트 섹션 이미지 path 오류 수정

[BugFix] Fix wrong img path

---

components/LayoutComponents/Footer.tsx
components/Products/CisLanding/Intro/Intro.tsx

최정윤
-  참여하기 페이지에서 footer에 스크롤 스냅 걸려있는 문제 해결 
- 그리너프 제품 소개 페이지 중 intro 페이지 : hover시 스크롤 잘 안넘어 가는 문제 해결

[BugFix] Fix bugs about scroll snap

---

components/HomeComponents/CardNonText/RightNonText.tsx
components/HomeComponents/MobileCards/MobileCards.tsx
components/Products/CietLanding/Process/NormalProcessSection.tsx

최정윤
- 루트 페이지 : 모바일 카드 보이는 비율 동일하게 수정 
- ciet 제품 페이지 : 기존 프로세스 부분 깨지는 문제 수정

[FeatDone] Update UI of mobile ver ciet page & root page

---

components/Products/CisLanding/Intro/Intro.tsx

최정윤
- 이미지에 스크롤 스냅 걸려있어, hover로 이미지 확대 시 화면 떨림현상 발생하는 문제 해결 
- 모바일 사진과 PC 사진을 분리하여, 모바일에서만 snap 적용되도록 변경함

[BugFix] Fix scroll is abnormal in intro section of greenerp page

---

components/LayoutComponents/NavBar.tsx

[Hotfix ] Add fashion LCA button

---

components/PopUp.tsx

최정윤
- 팝업에 세미나 후기 작성 버튼, 의류탄소 계산기 바로가기 버튼 추가 
- 팝업 쿠키관련 오류 수정

[FeatDone, Bugfix] Add btns to pop up & fix cookie bug 

---

components/PopUp.tsx

[Release] 2.3.0

---

components/LayoutComponents/NavBar.tsx

최정윤
패션 LCA 위의 new 모바일에서 매우 작게 보이는 문제 수정

[FeatDone] Fix ui bug

---

components/LayoutComponents/NavBar.tsx

최정윤
- 반응형 ui가 pc 버전에서 적용되는 문제 해결

[Bugfix ] Fix ui bug

---

components/Layout.tsx
components/LayoutComponents/Hamburger/HamburgerMenu.tsx
components/LayoutComponents/NavBar.tsx
pages/index.tsx
pages/lca/index.tsx

최정윤
- product section  제거 
- lca 문의 페이지로 대체

HOMEPAGE-36 [FeatDone] Repalce product section to lca section

---

components/Layout.tsx
components/LayoutComponents/Hamburger/HamburgerMenu.tsx
components/LayoutComponents/NavBar.tsx
pages/index.tsx
pages/lca/index.tsx

최정윤 
- product section 제거 
- LCA 문의 페이지로 대체

[Release] 2.8.0

---

components/RAndDComponents/LCA.tsx

HOMEPAGE-37 [Hotfix] 2.8.1

---

components/PopUp.tsx

[Hotfix] 2.8.3

---

components/LayoutComponents/NavBar.tsx
pages/index.tsx

최정윤
- fashion LCA 숨김 처리 
- 메인 페이지 레이아우 수정

[Release] 2.8.4

---

components/LayoutComponents/Footer.tsx
components/LayoutComponents/NavBar.tsx
pages/index.tsx

최정윤
- footer 전화번호 삭제 
- 탄소회계 산정툴 숨김 처리

[Release] 2.8.6

---

.gitignore
components/LayoutComponents/Footer.tsx
components/PopUp.tsx
package.json
pages/lca/index.tsx
pages/participate/index.tsx
yarn.lock

최정윤
HOMEPAGE-43
타입폼 -> 왈라로 대체 
HOMEPAGE-44
3차 세미나 팝업 -> 포브스 팝업으로 변경

[Patch] Replace popup & replace typeform to walla
